Tasks solved
js-tasks-ru/js-20220909_kuchurov pull request #2
Opened 2022-09-21 20:19 UTC by Kuchurov

В четвёртой задаче поправил файл тестов, указан был путь на папку с решениями, из-за этого сыпались тесты.

2022-09-21 20:20 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-23 10:34 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return param === 'desc' ? sorted.reverse() : sorted
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-09-23 10:34 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  let result = {}
`const result`

2022-09-23 10:35 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    if (obj[key]) result[key] = obj[key]
используйте `hasOwn`

2022-09-23 10:35 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  path = path?.split('.') || path
не мутируйте аргументы ф-ции, объявите дополнительную переменную

2022-09-23 10:35 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  const result = Object.fromEntries(Object.entries(obj).map(
👍 good

2022-09-23 10:36 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  let regexp = new RegExp('(?=(.))\\1{' + size + ',}', 'g')
решение нужно переделать, решать регуляркой нельзя!

загляните в `readme.md`

<img width="715" alt="image" src="https://user-images.githubusercontent.com/7078894/191943222-1f2ad4fc-164c-4a6e-b6ea-edfc360cab5d.png">

2022-09-23 10:37 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +  update(newData) {
good 👍
было бы неплохо задать значение по умолчанию для `newData`

2022-09-23 10:37 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +
почему метод пустой?

2022-09-23 10:38 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +  createElement(html) {
good 👍

2022-09-23 10:39 UTC, dosandk requested changes
`ColumnChart` - good 👍 но посмотрите сегодняшний разбор
по остальным задачам - внесите изменения согласно комментариев

2022-09-27 12:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-27 13:08 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-29 13:06 UTC, dosandk approved these changes
good 👍

2022-09-29 13:07 UTC, merged